### ISSUE TITLE
Login does not work with WinBiap 4.4

### ISSUE THREAD

**Issue by mayrstefan** [opacapp/opacclient#364]
Login to a library using WinBiap 4.4 does not work. There are two issues:
- login requires additional input fields to be sent (verified stripping them through burp proxy)
- list of lent books and other operations require the session cookie from the login form

**Comment by mayrstefan** [comment]
Patch to
- use a cookie store for operations known to need it
- generic approach to pass all input fields with two leading underscores in its id to the login form

[WinBiap4.4Cookies.patch.zip](https://github.com/opacapp/opacclient/files/101576/WinBiap4.4Cookies.patch.zip)

**Comment by raphaelm** [comment]
Looks good to me. @johan12345, what do you think?

**Comment by johan12345** [comment]
@mayrstefan 
- Did you try if it works without a custom `CookieStore`? The normal HTTP implementation _should_ already save and send cookies, the custom `CookieStore` should only be needed if you need to do something special with the cookies (e.g. access their values or modify them)
- In this case it probably doesn't matter because the values are the same (I didn't check but that's what I remember), but I think that in the POST data, the input fields are identified by their `name` attribute instead of their `id`, so in line 55 `inputField.attr("name")` should be used instead.

**Comment by mayrstefan** [comment]
@johan12345 
- afaik HttpClient requires a HttpContext to pass cookies between requests. As I can see in the BaseApi implementation context is only passed between requests when a cookie store is provided to the method. So using httpGet/httpPost without providing the cookie store should not work - i will verify this later
- you are right: for post data name should be used instead of id to make it more robust for future changes. For my library id equal name values and i choose id because i replaced the selector (#).

**Comment by mayrstefan** [comment]
@johan12345: i tested it and you are right - there is no need to modify httpGet/httpPost requests. I also changed the attribute from id to name and created a new patch file

[WinBiap4.4reduced.patch.zip](https://github.com/opacapp/opacclient/files/102021/WinBiap4.4reduced.patch.zip)

**Comment by raphaelm** [comment]
Committed in 01f2e602a5f58d3d5c6382440cadc2fe83b2c971.

@johan12345 We have this "construct a List<NameValuePair> from all input fields that match a selector" now very often in different APIs (Adis is full of it, for example). Let's keep in mind to abstract this into a nice helper function if it occurs the next time ;)

**Comment by johan12345** [comment]
@mayrstefan Thanks for the patch and for testing the cookie handling again!

@raphaelm Yes, good idea. Maybe we should do this together with the planned replacement of the deprecated Apache HTTP Client. It would also be usable for the places where [Open, WinBiap (in another location) and PICA LBS](https://github.com/opacapp/opacclient/search?utf8=%E2%9C%93&q=formdata) use JSoup's [`FormElement.formData()`](http://jsoup.org/apidocs/org/jsoup/nodes/FormElement.html#formData--) for a similar use case (create list from all input fields in a form) which unfortunately returns a `List<Connection.KeyVal>` instead of the `List<NameValuePair>` we need for the HTTPClient.

**Comment by raphaelm** [comment]
For the record, I don't think formData will work out, as Adis highly depends on partial form submits. But we'll find a nice solution if time comes.

**Comment by johan12345** [comment]
@mayrstefan Could you check if prolonging lent items works for you in the app? We have received reports from users in other WinBiap 4.4 libraries that the app only shows a progress dialog, but the return date does not change.

**Comment by mayrstefan** [comment]
This week I tried to prolong a book: the return date increased 14 days
Current used version is 4.5.3

**Comment by johan12345** [comment]
Thanks, I think we already fixed that problem with help from a library.
