### ISSUE TITLE
Why does your app need to run at system startup? (autostart)

### ISSUE THREAD

**Issue by rugk** [opacapp/opacclient#402]
Why does your app need this autostart? I see no reason why your app should be running in the background.

**Comment by johan12345** [comment]
The app is able to send notifications when lent books are due. When this feature is activated in the settings and you have set up a library account, it refreshes the due dates from the library server regularly (normally twice a day). These refreshes need to be scheduled at system startup because Android cancels them when the device is rebooted.

**Comment by rugk** [comment]
But I have not activated this setting and this app still *uses* autostart...

**Comment by johan12345** [comment]
That's because as far as I know, it is not possible to dynamically deactivate or activate autostart for your app when settings are changed. The RECEIVE_BOOT_COMPLETED permission obviously needs to be requested and also the BroadcastReceiver that runs on boot cannot be disabled dynamically. However, the app will *do* nothing on boot if the setting is disabled.

**Comment by rugk** [comment]
Okay, thanks for your information.
