### ISSUE TITLE
Replace icon with material icon

### ISSUE THREAD

**Issue by sedrubal** [opacapp/opacclient#452]
The app uses material design for the views, but the icon doesn't. Do you want to replace it with a more material icon?

**Comment by raphaelm** [comment]
You mean the main app icon? Well, if we had a material icon that we like more than the current one and that we can legally use, we'd be happy to do so.

**Comment by sedrubal** [comment]
Yes, the main app icon.

I'm not a designer and I don't really like the drafts (especially the colours) but this are some suggestions:

![opac](https://cloud.githubusercontent.com/assets/5571650/18608500/225fbeb0-7ceb-11e6-9051-71ab05644d47.png)
![opac2](https://cloud.githubusercontent.com/assets/5571650/18608501/2261e172-7ceb-11e6-9a67-3abf5b5d0fa7.png)

As SVG: https://gist.github.com/sedrubal/f1c276d826d114698944ff99c22134a0

**Comment by raphaelm** [comment]
Hey,
thank you for taking your time doing these drafts, I really appreciate that. But as you said, they are probably not a perfect fit. We're not designers either, which is why we haven't redesigned new icons ourserlves. Also, I believe the current icon has a good level of brand recognition that is hard to achieve by just showing a single generic book.

**Comment by johan12345** [comment]
With the current release, we have introduced a new icon.
