### ISSUE TITLE
Account support for OPEN

### ISSUE THREAD

**Issue by privacy-wolf** [opacapp/opacclient#481]
Unfortunately, the access to the "Stadtbücherei Tübingen" doesn't work anymore. It did work in the past but stopped working some time ago. I recognized that their webpage also seem to have changed quite substantially, so I would assume they changed systems (their api) probably. I'm happy to try to provide more details if someone would let me know what is needed to dig into the root cause of the issue.

![screenshot - stadtbucherei tubingen](https://cloud.githubusercontent.com/assets/26414712/26523031/a033307c-430d-11e7-8727-ebb5b1732878.png)

**Comment by johan12345** [comment]
Hi,

yes, the library has switched to another software (*Bibliotheca OPEN*) recently. For this software, we currently only support the catalog search and not the account features. So the message that the app shows is indeed correct.

Because our app connects to the online catalogue websites of the libraries and scrapes data from the HTML (apart from very few exceptions, there are no APIs for this), implementing support for a new software is a large amount of work. We have started to implement the account features for *OPEN*, but we have decided to keep this code closed-source for now to make it available exclusively in the [Plus Edition](https://de.opacapp.net/fur-bibliotheken/) of our app, which we sell to libraries and also includes additional features. As many libraries are switching to *OPEN* these days, this is a good selling point.

We will sooner or later also add it to the open source version, but to keep the open source app sustainable, we need more customers for the Plus Edition. Currently, we can only afford to do basic support and maintenance and we are not building new features :(

If you'd like, you could try to contact your library and suggest them to buy our Plus Edition. This usually meets more interest when it is suggested by the library's users rather than ourselves.

**Comment by privacy-wolf** [comment]
Thanks for your reply!
Since I'm an advocate of open source the plus version (which is closed source) is not an option from my viewpoint so this is nothing I could suggest to any library.
If I don't misunderstand it, an installation of the plus version would even require access Google's Play store which also is a no-go from my viewpoint (in my case I don't have this store, just F-Droid).

**Comment by johan12345** [comment]
> Since I'm an advocate of open source the plus version (which is closed source) is not an option from my viewpoint so this is nothing I could suggest to any library.

Well, that's what we are too. But this project is so large that it requires a huge amount of maintenance and support work, which is not something the two of us (@raphaelm and me) are able to do in our spare time - and the app didn't have substantial contributions from other people in the recent past.

Offering paid maintenance/support for open source software or selling products that are based on OSS is a very common business model.

> If I don't misunderstand it, an installation of the plus version would even require access Google's Play store which also is a no-go from my viewpoint (in my case I don't have this store, just F-Droid).

Yes, currently the Plus Edition apps are only available on Google Play - F-Droid would not accept them as they are not open source. However, we are investigating if we can provide an own repository compatible with F-Droid where these apps could then be downloaded.

**Comment by johan12345** [comment]
Since 04125ba41907fecb8bb220ef448161ed07abb62c, we have support for the account features in the open source version of the app, which we will enable for all libraries with a support contract (see https://opac.app/de/support-policy/).

But Stadtbücherei Tübingen has switched to another system, LMSCloud, in January 2019, and account features for that are supported as well.
