### ISSUE TITLE
Media without title (e.g. individual journal issues)

### ISSUE THREAD

**Issue by StefRe** [opacapp/opacclient#516]
At least at Dresden municipal library, individual journal issues have no title. In this case it's not possible to identify the journal/issue in the app's display:

![grafik](https://user-images.githubusercontent.com/19879328/39979934-95272f7a-5749-11e8-9b78-70587b3c5304.png)

The desktop WebOPAC client of the library shows additional information on the second line:

![grafik](https://user-images.githubusercontent.com/19879328/39979936-9d16d23a-5749-11e8-9e98-bc4ddfcee607.png)

Could you either
a) include the barcode number and journal issue name ("Landlust 17/3-4" in the attached example) in the detailed information view (shown when clicking on the item)  or

b) replace an empty title with the journal issue name in the overview view or

c) both of the abobe

**Comment by johan12345** [comment]
Hi, thanks for the bug report! I think we should be able to implement both of the suggestions. As we don't have an account at Dresden library, it would be great if you could send us the HTML source code of the list of lent items on the library website (second screenshot) to info@opac.app so that we can test this.

**Comment by StefRe** [comment]
I'v sent the code to info@opac.app but I'm not sure if this is of any help as I doesn't show any information as of what OPAC database fields this information comes from. The lent items list is generated by [accountData.jsp](http://katalog.bibo-dresden.de/webOPACClient/jsp/useraccount/accountdata/accountData.jsp).

**Comment by johan12345** [comment]
Thanks!

> I'v sent the code to info@opac.app but I'm not sure if this is of any help as I doesn't show any information as of what OPAC database fields this information comes from.

Our app doesn't actually access the library's database - for most OPAC systems (including this one), there is no other way for us to access the data than scraping it from the HTML of the OPAC web interface.

I have added support for detecting the barcode (always) and journal issue (if there is no title) with 164ebe35, so this problem should be fixed in the next app update.

**Comment by johan12345** [comment]
The update should be available in the Google Play Store in a few hours (if you installed the app from F-Droid, it might take longer - we don't have control over their build server).
