### ISSUE TITLE
Changed OPAC software Stadtbücherei Tübingen

### ISSUE THREAD

**Issue by tschach** [opacapp/opacclient#555]
Hi,

the Stadtbücherei Tübingen changed there OPAC software and URL, it is now available at https://sb-tuebingen.lmscloud.net/cgi-bin/koha/opac-main.pl

Will Web Opac be able to support this library in the future again? Would be awesome!

Thanks and best,
Tobias

**Comment by johan12345** [comment]
Hi,

we do support the new software (Koha / LMSCloud) since #533. I have [update the configuration](https://github.com/opacapp/opacapp-config-files/commit/176b4ab55b78866d3e22bf041ce2179507fbd616), so when you tap the button to download the updated configuration files in the app's settings, it should work again.
