### ISSUE TITLE
PICA: Change default sorting mode to "relevance"

### ISSUE THREAD

**Issue by AltNico** [opacapp/opacclient#557]
When I met @raphaelm the last time, I told him that I get "poor results" upon searching for books at "Universitäts- und Landesbibliothek Darmstadt".

I now found out why I got those "poor results": at least for this library, the default sorting mode is set to "year of publication". If I search for e.g. "Physik Tipler", I get pages and pages of results, but none contains the wanted book. If I change the sorting mode to "relevance", the wanted book shows up as one of the first results.

Therefore, I suggest to change the default sorting mode to "relevance". Note that this is also the default mode [if you search on the libary's web page](https://www.ulb.tu-darmstadt.de/service/start/index.de.jsp).

**Comment by raphaelm** [comment]
Interesting, I think we just default to the *first* sorting mode, as the app doesn't have any intelligence to recognize sorting modes?

**Comment by johan12345** [comment]
We use the older PICA catalogue at
https://pica1l.ulb.tu-darmstadt.de/DB=LHBDA/ADVANCED_SEARCHFILTER
for this library. There, the default selection is to sort by year of publication.

Also, yes, the API implementation currently does not have a way to tell the app which option should be the default, the app always uses the first one. But what we could do is tell the API to move the "relevance" option to the top of the list so that it's selected by default.

**Comment by johan12345** [comment]
I implemented this and it will be included in the next update of the app :)

**Comment by AltNico** [comment]
@johan12345 I've just tested it with the new F-Droid release and it works. Thanks a lot!
